### PR TITLE
needed

### PR DESCRIPTION
**Pull request by onukore**
hello , i love radium, this is my favorit soft after aodix , but it need some other stuff like : 
1- scroll lock for block, to work with playing sound (automation)
2- loop part of block like in aodix
3- automation rang copy and past (when a copy rang it dosen't copy automation juste note)
4- midi controler support ,and record direct in automation 
5- select rang with mouse
6- in sampler real loop with selector, and ping pong loop
7- one time register ex :one year at time 24€ ex, better for me
8- french keybord support 
9- in patchbay 16 out be better or 32 the best
10- more colors options ( ex rang colors diferent to back ground colors) :)

i want to make next EP with radium tracker, it's very nice for experimental music 
sorry for my english 
best regard
onukore

### CODE REVIEW

**Comment by kmatheussen** [comment]
Hi,

This should have been added to the issues: https://github.com/kmatheussen/radium/pulls

> 1- scroll lock for block, to work with playing sound (automation)

Existed before 3.0. Thought it was useless. See if it's simple to implement with the new graphics engine.
I'll make an issue.

> 2- loop part of block like in aodix

That's probably not going to happen unfortunately. Requires a lot of changes.


> 3- automation rang copy and past (when a copy rang it dosen't copy automation juste note)

I'll make an issue.


> 4- midi controler support ,and record direct in automation 

There is already an issue for this.


> 5- select rang with mouse

I'll make an issue.


> 6- in sampler real loop with selector, and ping pong loop

Do you mean a graphical sample editor where you can select start and stop loop points with the mouse?


> 7- one time register ex :one year at time 24€ ex, better for me

I'll see what I can do.


> 8- french keybord support

Can you be more specific what doesn't work? I can use norwegian keyboard.
And is it Windows, osx or linux?

**Comment by kmatheussen** [comment]
> 4- midi controler support ,and record direct in automation

I need some more info.

1. What do you mean exactly by "MIDI controller support"?

2. For "record direct in automation", do you mean that you want to create auotmation automatically from MIDI input while playing?

**Comment by kmatheussen** [comment]
> > 2- loop part of block like in aodix
> That's probably not going to happen unfortunately. Requires a lot of changes.

I misunderstood. I thought you meant running part of a block many times, for instance play line 4-8 5X  before continuing, like you can in many trackers. 

I think there is an  issue for looping the range. If not, I'll add it.

**Comment by onukore** [comment]
hello, kmatheussen thank for you're fast answer

--1 What do you mean exactly by "MIDI controller support"?

i mean , to asign directly controler from my mpk mini controler knob to parametre in instrument box
it work on vst have learn option ( not well ,not fluid , is jumping all time) ,but if not learn option i cant asign it 

--2 For "record direct in automation", do you mean that you want to create auotmation automatically from MIDI input while playing?
yes exactly that, on live rec ,and step by step rec ( create nod when move rotary knob)

--Can you be more specific what doesn't work? I can use norwegian keyboard.
And is it Windows, osx or linux? 

i use win 7 and in french keybord this is ( AZERTY) not (qwerty) if i press A first key in french keybord in aodix or renoise ect... note is c-4 , in radium this is note off , the key aren't in the same place , this is juste not easy to enter note :) ( french always more compliquated lol)

for loop rang i mean loop part of pattern for work , like all other daw , some time we need too work on 1/4 of block for automation ex, in radium we need too restart block , more time loosed, if you only work on ligne 48--> 64 for example

--6- in sampler real loop with selector, and ping pong loop
Do you mean a graphical sample editor where you can select start and stop loop points with the mouse?

sample editor not needed for that, juste loop start and loop end parametre , ping pong one shot etc..,like in Impulse tracker if we can see the marker in graph in track sampler , it s the best ( horizontal line red for start loop and bleu for end, or other colors)

**Comment by onukore** [comment]
i have forget  another think preset selection in instrument box on native, lot of plugins haven't previous an next preset option ,and programme change fx will be fine, transport for play, stop,rec, ect.... with controler midi and asignable volume,mute,mute, solo in the mixer 

I know that a lot of work , but with all this it will be the best tracker 
thanks you for you're work ,i wil buy radium soon

**Comment by kmatheussen** [comment]
(I'll reply to the rest later)

> i have forget another think preset selection in instrument box on native, 

I'm not sure what you mean here. Doesn't the load/save/replace buttons cover what you want?

**Comment by onukore** [comment]
how do I change preset with that ? in a bank there are several preset (0-127) , load one preset is not problem , problem in navigation in preset bank ( previous- next)

**Comment by kmatheussen** [comment]
I'm not quite sure what you mean yet. Could it be that the "Program change" effect in the "MIDI Messages" sound object would solve your problem?

**Comment by kmatheussen** [comment]
> i mean , to asign directly controler from my mpk mini controler knob to parametre in instrument box
it work on vst have learn option ( not well ,not fluid , is jumping all time) ,but if not learn option i cant asign it

Ah, midi learn? Yes, there an issue for it.

> yes exactly that, on live rec ,and step by step rec ( create nod when move rotary knob)

Made issue


> i use win 7 and in french keybord this is ( AZERTY) not (qwerty) if i press A first key in french keybord in aodix or renoise ect... note is c-4 , in radium this is note off , the key aren't in the same place , this is juste not easy to enter note :) ( french always more compliquated lol)

Made issue.


> for loop rang i mean loop part of pattern for work , like all other daw , some time we need too work on 1/4 of block for automation ex, in radium we need too restart block , more time loosed, if you only work on ligne 48--> 64 for example

Made issue. Think this can be hacked together quite easily. You can already start playing from range start by pressing left win + space, so it shouldn't be too hard to send a play range command every time the cursor reaches range end.

**Comment by kmatheussen** [comment]
> sample editor not needed for that, juste loop start and loop end parametre , ping pong one shot etc..,like in Impulse tracker if we can see the marker in graph in track sampler , it s the best ( horizontal line red for start loop and bleu for end, or other colors)

Made issue

**Comment by onukore** [comment]
sorry , I have given much work :)

--I'm not quite sure what you mean yet. Could it be that the "Program change" effect in the "MIDI Messages" sound object would solve your problem?

this is aodix program change with voyager vsti

capture d ecran 2015-08-10 15 47 01

**Comment by kmatheussen** [comment]
Ah, VST preset navigation. That's useful. Don't know why I've never thought of that.

**Comment by onukore** [comment]
Most hollowing out the stuff that we forget are often the most
in french we say : on peut pas penser a tous ( we can not think of any)
program change effect  in midi message needed too lol

**Comment by kmatheussen** [comment]
In the next release, you can select VST presets in the instrument widget, either by clicking the preset name button, or by changing the preset number. To select next preset, scroll the mouse wheel on the preset number up, and to select the previous preset, scroll the mouse wheel down. This was a quick fix actually. :-)

**Comment by onukore** [comment]
very nice !!

**Comment by onukore** [comment]
programme change work fine with midimessage , but it's hard to enter program wiched with automation curve, is it possible to enter with sliders ?

**Comment by kmatheussen** [comment]
Yes, there is a slider for "programme change" in the "midi message" sound object. You can also press ctrl while dragging for finetuning. But what is "point automation"?

**Comment by onukore** [comment]
hi i have make the donation for one year , i want my full version looooooool

**Comment by onukore** [comment]
capture d ecran 2015-08-15 15 50 45

line automation

capture d ecran 2015-08-15 15 51 01

piont automation

**Comment by kmatheussen** [comment]
Oh, right. Yes, point automation shouldn't be too much work implementing. I'll make a separate issue about it.

**Comment by onukore** [comment]
is possible if in track ,the point option is actived , keep only the nod and Erasing the line ?

**Comment by kmatheussen** [comment]
I'll just do point automation first. One thing at the time. :-)

I'm closing this pull request now, since it's not a pull request. Please make a new issue for each new topic. There's less chance for things to be forgotten then.

**Pull request closed without merging**
