### PR TITLE
Demo song where all instruments are made with FAUST

### PR DESCRIPTION
**Pull request by ngeiswei**
Not sure if that is how demo songs are submitted, but here it is.  Beware that it takes a very long time to load, probably due to FAUST compilation time.

### CODE REVIEW

**Comment by kmatheussen** [comment]
Thank you very much, a really lovely song! I'm adding it to the File->Demo Songs menu (I assume that's okay).

And sorry for late reply. I must have overlooked the email notification. I've also marked your subscription as permanent so that you will keep it forever.

**Comment by kmatheussen** [comment]
Oh, wow. Have you written all the instruments yourself from scratch? That's a REALLY great demo for the program. I need to make this feature more visible somehow.

**Comment by ngeiswei** [comment]
Thanks @kmatheussen!  Yes, beside Karplus and Voice, I have written every instrument from scratch.  I think the built-in support for FAUST is a hidden gem of Radium.

**Comment by kmatheussen** [comment]
I'm disabling the song from menus of the 32 bit Windows version of Radium. Seems like Radium runs out of memory very quickly, and crashes, after this song has been loaded. I don't know though if there's something wrong in the 32 bit windows version, or if it's legitimately temporarily using more than 2GB of memory (in which case it doesn't make sense trying to fix it), but it doesn't seem to happen on any other platform.

**Comment by kmatheussen** [comment]
@ngeiswei There's a bug in Radium when releasing Faust notes.It's been fixed in 0c86614b11edb73ad4079241701224e026968fbb (there's been no release yet which includes this commit though). The bug has been there for 12 years! Quite emberrasing, obviously I never tested that release worked properly.

What happened was that release didn't work at all. E.g. `en.adsre(0.025,0.1,0.4,0.4,gate);` did the same as  `en.adsre(0.025,0.1,0.4,0.0,gate);`.

For compatibility, old songs are loaded with the old buggy behavior, so Poptikus still sounds the same. However, if I go to File -> Song Preferences and turn off the buggy behavior, the song sounds notably different. I even think that sometimes it sounds quite a bit better! (E.g. the arpeggio of the intro arguably sounds better with the buggy release-behavior turned off).

Perhaps you want to look at the song again with the buggy release-behavior turned off?

**Comment by ngeiswei** [comment]
Ah, I knew it!  Great to know it's been fixed, I will have a look at it and provide an updated song within the coming weeks.  Thanks for the notification.

**Comment by ngeiswei** [comment]
OK, I finally have time to look into it, however since there has been no release I need to compile Radium from source, which I find a bit daunting.  Thus I wanted to ask, do you think a release with the fixed behavior is coming soon, or I need to compile it from source?

**Comment by kmatheussen** [comment]
Ouch, I don't have the linux computer right now, just a mac. It'll have to
wait until wednesday.

**Comment by ngeiswei** [comment]
No problem, that can wait.

**Comment by kmatheussen** [comment]
Here's V1.77 for Linux:

https://users.notam02.no/~kjetism/radium/radium_64bit_linux-7.4.77.tar.xz

It includes all commits up and including this one:
https://github.com/kmatheussen/radium/commit/0c86614b11edb73ad4079241701224e026968fbb
(but no commits after)

**Pull request merged**
