### PR TITLE
Build: Update FAUST package from 20191222-dev to 2.27.2-stable

### PR DESCRIPTION
**Pull request by Teteros**
This updates the FAUST 2019-12-22 build to latest stable 2.27.2 (2020-08-04) release.
Tested on Arch Linux x64 and Radium 6.5.77 FAUSTDEV instrument works well with this.

The reason for the update is because I was originally going to backport LLVM10 and 11 support but it turned out to be a lot of commits, at least
https://github.com/grame-cncm/faust/commit/a47be313dece04aa1c73eceaa86ce627df43038a
https://github.com/grame-cncm/faust/commit/bf654d6aa906a4e5edb356599f149a092677bdd0
https://github.com/grame-cncm/faust/commit/391740489507b76e3f6aecbc9dd5b0f75f8aae22
[...]

Note that it looks like FAUST requires LLVM8 or later now:
https://github.com/grame-cncm/faust/commit/bf50ef0c109bf3dadde849d2a5253f181f6699e4

so if you do use LLVM7 or earlier locally this might have to wait.

### CODE REVIEW

**Comment by kmatheussen** [comment]
Thank you! I don't know right now which version of LLVM that is used to compile the binary packages. I guess they are older than LLVM7 though. It's probably time to upgrade the binary packages soon though, I'm still on Qt 5.12 for instance, and the linux glib is so old that it sometimes creates problems on newer distributions.

**Comment by kmatheussen** [comment]
(I meant linux glibc, not glib)

**Comment by Teteros** [comment]
> I'm still on Qt 5.12 for instance, and the linux glib is so old that it sometimes creates problems on newer distributions.

The `libstdc++.so.6` file right? Yes, still have to delete this for the radium-bin package.
Also Selinux being linked is still an issue in the binary packages by the way

```sh
$ LD_LIBRARY_PATH=lib:$LD_LIBRARY_PATH ldd bin/radium_linux.bin | grep selinux
        libselinux.so.1 => not found
        libselinux.so.1 => not found
```

**Comment by kmatheussen** [comment]
Looks like I'm using llvm 8 on both windows and mac so I'll probably merge it if it looks okay.

**Comment by kmatheussen** [comment]
Planning to merge this and update to JUCE 6 (https://github.com/kmatheussen/radium/issues/1259) in January. I don't want to mess to much around right now with the computer used for compilation since I only have access to it remotely.

**Pull request merged**
